FROM golang:1.20-alpine

RUN mkdir -p /go/src/github.com/k1ng2193/local-kms
COPY . /go/src/github.com/k1ng2193/local-kms

WORKDIR /go/src/github.com/k1ng2193/local-kms

RUN apk add --no-cache --update git \
    && go install github.com/bokwoon95/wgo@latest

RUN mkdir /data

ENV KMS_ACCOUNT_ID 111122223333
ENV KMS_REGION us-east-2
ENV KMS_DATA_PATH /data

ENV PORT 8080

ENTRYPOINT ["wgo", "run", "start.go"]
