version: "3"

services:
  kms:
    container_name: local-kms-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/github.com/k1ng2193/local-kms
      - ./test_seed.yaml:/init/seed.yaml
      - ./data:/data
    ports:
      - 4566:8080
      - 4599:8080
